BEGIN;
DROP TABLE IF EXISTS `humidity`;
CREATE TABLE IF NOT EXISTS `humidity` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`humidity`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	BIGINT NOT NULL
)
COLLATE='utf8_bin'
;
DROP TABLE IF EXISTS `temperature`;
CREATE TABLE IF NOT EXISTS `temperature` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`temperature`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	BIGINT NOT NULL
)
COLLATE='utf8_bin'
;
DROP TABLE IF EXISTS `pressure`;
CREATE TABLE IF NOT EXISTS `pressure` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`pressure`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	BIGINT NOT NULL
)
COLLATE='utf8_bin'
;
DROP TABLE IF EXISTS `position`;
CREATE TABLE IF NOT EXISTS `position` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`longitude`	REAL NOT NULL,
	`latitude`	REAL NOT NULL,
	`altitude`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	BIGINT NOT NULL
)
COLLATE='utf8_bin'
;
DROP TABLE IF EXISTS `orientation`;
CREATE TABLE IF NOT EXISTS `orientation` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`missionID`	TEXT NOT NULL,
	`x`	REAL NOT NULL,
	`y`	REAL NOT NULL,
	`z`	REAL NOT NULL,
	`w`	REAL NOT NULL,
	`time`	BIGINT NOT NULL
);
DROP TABLE IF EXISTS `missions`;
CREATE TABLE IF NOT EXISTS `missions` (
	`id`	BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	`missionID`	TEXT NOT NULL,
	`time`	BIGINT NOT NULL
)
COLLATE='utf8_bin'
;
COMMIT;
